import '../models/book_model.dart';

class MockDataService {
  static List<BookModel> books = [
    BookModel(
      id: 1,
      title: 'Atomic Habits',
      author: 'James Clear',
      price: 15000,
      oldPrice: 20000,
      discount: 25,
      image: 'assets/images/atomic_habits.jpg',
      category: 'Business',
      rating: 4.8,
      reviews: 1200,
      description: 'Changer ses habitudes pour transformer sa vie.',
      publisher: 'Penguin',
      pages: 320,
      isbn: '9780735211292',
      inStock: true,
      releaseDate: DateTime(2018, 10, 16),
    ),

    BookModel(
      id: 2,
      title: 'Python Programming',
      author: 'John Smith',
      price: 18000,
      oldPrice: null,
      discount: null,
      image: 'assets/images/python.jpg',
      category: 'Informatique',
      rating: 4.5,
      reviews: 850,
      description: 'Apprendre Python étape par étape.',
      publisher: 'O’Reilly',
      pages: 420,
      isbn: '9781492051367',
      inStock: true,
      releaseDate: DateTime(2021, 6, 10),
    ),

    BookModel(
      id: 3,
      title: 'Rich Dad Poor Dad',
      author: 'Robert Kiyosaki',
      price: 12000,
      oldPrice: 14000,
      discount: 15,
      image: 'assets/images/rich_dad.jpg',
      category: 'Business',
      rating: 4.7,
      reviews: 980,
      description: 'Éducation financière moderne.',
      publisher: 'Plata',
      pages: 336,
      isbn: '9781612680194',
      inStock: true,
      releaseDate: DateTime(2017, 4, 11),
    ),

    BookModel(
      id: 4,
      title: 'The Little Prince',
      author: 'Antoine de Saint-Exupéry',
      price: 8000,
      oldPrice: null,
      discount: null,
      image: 'assets/images/little_prince.jpg',
      category: 'Romans',
      rating: 4.9,
      reviews: 3000,
      description: 'Un conte poétique et philosophique.',
      publisher: 'Gallimard',
      pages: 96,
      isbn: '9780156013987',
      inStock: true,
      releaseDate: DateTime(1943, 4, 6),
    ),
  ];
}
